compile: null
data:
  drop_last: true
  num_workers: 32
  pad_direction: right
  paths:
  - s3://ai2-llm/preprocessed/olmo-mix/v1_6-decontaminated/books/gpt-neox-olmo-dolma-v1_5/part-0-00000.npy
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 8
  timeout: 0
device_eval_batch_size: ${device_train_microbatch_size}
device_train_microbatch_size: 16
dry_run: false
eval_interval: ${save_interval}
eval_on_load: true
eval_subset_num_batches: -1
evaluators:
- label: math_algebra
  type: downstream
- label: math_counting_and_prob
  type: downstream
- label: math_geometry
  type: downstream
- label: math_intermediate_algebra
  type: downstream
- label: math_num_theory
  type: downstream
- label: math_prealgebra
  type: downstream
- label: math_precalc
  type: downstream
- label: math_asdiv
  type: downstream
fsdp:
  precision: mixed
  wrapping_strategy: by_block_and_size
global_train_batch_size: 512
load_path: null
<<<<<<< Updated upstream
max_duration: 50e9T
=======
max_duration: 2
>>>>>>> Stashed changes
max_grad_norm: 1.0
max_grad_norm_ratio: null
model:
  activation_type: swiglu
  alibi: false
  attention_dropout: 0.0
  attention_layer_norm: false
  attention_layer_norm_with_affine: false
  bias_for_layer_norm: false
  block_type: sequential
  clip_qkv: 8.0
  d_model: 576
  embedding_dropout: 0.0
  embedding_size: 50304
  eos_token_id: 0
  flash_attention: true
  include_bias: false
  init_device: meta
  init_fn: mitchell
  layer_norm_type: default
  layer_norm_with_affine: false
  max_sequence_length: 2048
  mlp_ratio: 8
  multi_query_attention: false
  n_heads: 8
  n_layers: 24
  pad_token_id: 1
  residual_dropout: 0.0
  rope: true
  rope_full_precision: true
  vocab_size: 50280
  weight_tying: false
no_pre_train_checkpoint: true
optimizer:
  betas:
  - 0.9
  - 0.95
  decay_embeddings: true
  decay_norm_and_bias: true
  learning_rate: 0.0004
  metrics_log_interval: 10
  name: adamw
  weight_decay: 0.1
precision: amp_bf16
remote_save_folder: null
reset_optimizer_state: false
reset_trainer_state: false
restore_dataloader: false
run_name: no_flan_olmo-154m
<<<<<<< Updated upstream
save_folder: /data/tain
save_interval: 2000
save_interval_unsharded: 2000
=======
save_folder: ''
save_interval: 1000
save_interval_unsharded: 1000
>>>>>>> Stashed changes
save_num_checkpoints_to_keep: -1
save_num_unsharded_checkpoints_to_keep: -1
save_overwrite: true
scheduler:
  alpha_f: 0.1
  grad_clip_warmup_factor: 5
  grad_clip_warmup_steps: 1666666666
  name: cosine_with_warmup
  t_max: 50000000000
  t_warmup: 3333333333
  units: tokens
seed: 61394
sharded_checkpointer: olmo_core
speed_monitor:
  window_size: 1
<<<<<<< Updated upstream
stop_at: 47693
=======
stop_at: 2
>>>>>>> Stashed changes
time_limit: null
tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right
wandb: null
